name = "cmsis"
description = "CMSIS Version 5"
version = "5.7.0" 

[cmake]
	include = "cmake/cmsis.cmake"
	
[packaging]
	include = [
		"cmake",
		"cmsis",
		"LICENSE",
		"README.md",
		"src"
	]

[arch]

[arch.ARMCM0]
definition = "cmake/ARMCM0.cmake"
cpu = "Cortex-M0"

[arch.ARMCM0P]
definition = "cmake/ARMCM0P.cmake"
cpu = "Cortex-M0+"

[arch.ARMCM0P_MPU]
definition = "cmake/ARMCM0P_MPU.cmake"
cpu = "Cortex-M0+"

[arch.ARMCM1]
definition = "cmake/ARMCM1.cmake"
cpu = "Cortex-M1"

[arch.ARMCM3]
definition = "cmake/ARMCM3.cmake"
cpu = "Cortex-M3"

[arch.ARMCM4]
definition = "cmake/ARMCM4.cmake"
cpu = "Cortex-M4"

[arch.ARMCM4_FP]
definition = "cmake/ARMCM4_FP.cmake"
cpu = "Cortex-M4"

[arch.ARMCM7]
definition = "cmake/ARMCM7.cmake"
cpu = "Cortex-M7"

[arch.ARMCM7_SP]
definition = "cmake/ARMCM7_SP.cmake"
cpu = "Cortex-M7"

[arch.ARMCM7_DP]
definition = "cmake/ARMCM7_DP.cmake"
cpu = "Cortex-M7"

[arch.ARMCM23]
definition = "cmake/ARMCM23.cmake"
cpu = "Cortex-M23"

[arch.ARMCM23_TZ]
definition = "cmake/ARMCM23_TZ.cmake"
cpu = "Cortex-M23"

[arch.ARMCM33]
definition = "cmake/ARMCM33.cmake"
cpu = "Cortex-M33"

[arch.ARMCM33_TZ]
definition = "cmake/ARMCM33_TZ.cmake"
cpu = "Cortex-M33"

[arch.ARMCM33_DSP_FP]
definition = "cmake/ARMCM33_DSP_FP.cmake"
cpu = "Cortex-M33"

[arch.ARMCM33_DSP_FP_TZ]
definition = "cmake/ARMCM33_DSP_FP_TZ.cmake"
cpu = "Cortex-M33"

[arch.ARMCM35P]
definition = "cmake/ARMCM35P.cmake"
cpu = "Cortex-M35P"

[arch.ARMCM35P_TZ]
definition = "cmake/ARMCM35P_TZ.cmake"
cpu = "Cortex-M35P"

[arch.ARMCM35P_DSP_FP]
definition = "cmake/ARMCM35P_DSP_FP.cmake"
cpu = "Cortex-M35P"

[arch.ARMCM35P_DSP_FP_TZ]
definition = "cmake/ARMCM35P_DSP_FP_TZ.cmake"
cpu = "Cortex-M35P"

[arch.ARMCM55]
definition = "cmake/ARMCM55.cmake"
cpu = "Cortex-M55"

[arch.ARMSC000]
definition = "cmake/ARMSC000.cmake"
cpu = "SC000"

[arch.ARMSC300]
definition = "cmake/ARMSC300.cmake"
cpu = "SC300"

[arch.ARMv8MBL]
definition = "cmake/ARMv8MBL.cmake"
cpu = "ARMV8MBL"

[arch.ARMv8MML]
definition = "cmake/ARMv8MML.cmake"
cpu = "ARMV8MML"

[arch.ARMv8MML_DSP]
definition = "cmake/ARMv8MML_DSP.cmake"
cpu = "ARMV8MML"

[arch.ARMv8MML_SP]
definition = "cmake/ARMv8MML_SP.cmake"
cpu = "ARMV8MML"

[arch.ARMv8MML_DSP_SP]
definition = "cmake/ARMv8MML_DSP_SP.cmake"
cpu = "ARMV8MML"

[arch.ARMv8MML_DP]
definition = "cmake/ARMv8MML_DP.cmake"
cpu = "ARMV8MML"

[arch.ARMv8MML_DSP_DP]
definition = "cmake/ARMv8MML_DSP_DP.cmake"
cpu = "ARMV8MML"

[arch.ARMv81MML_DSP_DP_MVE_FP]
definition = "cmake/ARMv81MML_DSP_DP_MVE_FP.cmake"
cpu = "ARMV81MML"

[arch.ARMCA5]
definition = "cmake/ARMCA5.cmake"
cpu = "Cortex-A5"

[arch.ARMCA7]
definition = "cmake/ARMCA7.cmake"
cpu = "Cortex-A7"

[arch.ARMCA9]
definition = "cmake/ARMCA9.cmake"
cpu = "Cortex-A9"

