[project]
	type = "library"
	name = "cmsis"
	description = "CMSIS Version 5"
	version = "5.6.0" 

	[project.cmake]
		include = [
			"cmake/cmsis.cmake"	
		]
	
[packaging]
	include = [
		"cmake",
		"cmsis"
	]
