name = "cmsis"
description = "CMSIS Version 5"
version = "5.7.0" 

[cmake]
	include = "cmake/cmsis.cmake"
	
[packaging]
	include = [
		"cmake",
		"cmsis",
		"LICENSE",
		"README.md",
		"src"
	]

[arch]

[arch.ARMCM0]
cpu = "Cortex-M0"
definition = "cmake/ARMCM0.cmake"

[arch.ARMCM0P]
cpu = "Cortex-M0+"
definition = "cmake/ARMCM0P.cmake"

[arch.ARMCM0P_MPU]
cpu = "Cortex-M0+"
definition = "cmake/ARMCM0P_MPU.cmake"

[arch.ARMCM1]
cpu = "Cortex-M1"
definition = "cmake/ARMCM1.cmake"

[arch.ARMCM3]
cpu = "Cortex-M3"
definition = "cmake/ARMCM3.cmake"

[arch.ARMCM4]
cpu = "Cortex-M4"
definition = "cmake/ARMCM4.cmake"

[arch.ARMCM4_FP]
cpu = "Cortex-M4"
definition = "cmake/ARMCM4_FP.cmake"

[arch.ARMCM7]
cpu = "Cortex-M7"
definition = "cmake/ARMCM7.cmake"

[arch.ARMCM7_SP]
cpu = "Cortex-M7"
definition = "cmake/ARMCM7_SP.cmake"

[arch.ARMCM7_DP]
cpu = "Cortex-M7"
definition = "cmake/ARMCM7_DP.cmake"

[arch.ARMCM23]
cpu = "Cortex-M23"
definition = "cmake/ARMCM23.cmake"

[arch.ARMCM23_TZ]
cpu = "Cortex-M23"
definition = "cmake/ARMCM23_TZ.cmake"

[arch.ARMCM33]
cpu = "Cortex-M33"
definition = "cmake/ARMCM33.cmake"

[arch.ARMCM33_TZ]
cpu = "Cortex-M33"
definition = "cmake/ARMCM33_TZ.cmake"

[arch.ARMCM33_DSP_FP]
cpu = "Cortex-M33"
definition = "cmake/ARMCM33_DSP_FP.cmake"

[arch.ARMCM33_DSP_FP_TZ]
cpu = "Cortex-M33"
definition = "cmake/ARMCM33_DSP_FP_TZ.cmake"

[arch.ARMCM35P]
cpu = "Cortex-M35P"
definition = "cmake/ARMCM35P.cmake"

[arch.ARMCM35P_TZ]
cpu = "Cortex-M35P"
definition = "cmake/ARMCM35P_TZ.cmake"

[arch.ARMCM35P_DSP_FP]
cpu = "Cortex-M35P"
definition = "cmake/ARMCM35P_DSP_FP.cmake"

[arch.ARMCM35P_DSP_FP_TZ]
cpu = "Cortex-M35P"
definition = "cmake/ARMCM35P_DSP_FP_TZ.cmake"

[arch.ARMCM55]
cpu = "Cortex-M55"
definition = "cmake/ARMCM55.cmake"

[arch.ARMSC000]
cpu = "SC000"
definition = "cmake/ARMSC000.cmake"

[arch.ARMSC300]
cpu = "SC300"
definition = "cmake/ARMSC300.cmake"

[arch.ARMv8MBL]
cpu = "ARMV8MBL"
definition = "cmake/ARMv8MBL.cmake"

[arch.ARMv8MML]
cpu = "ARMV8MML"
definition = "cmake/ARMv8MML.cmake"

[arch.ARMv8MML_DSP]
cpu = "ARMV8MML"
definition = "cmake/ARMv8MML_DSP.cmake"

[arch.ARMv8MML_SP]
cpu = "ARMV8MML"
definition = "cmake/ARMv8MML_SP.cmake"

[arch.ARMv8MML_DSP_SP]
cpu = "ARMV8MML"
definition = "cmake/ARMv8MML_DSP_SP.cmake"

[arch.ARMv8MML_DP]
cpu = "ARMV8MML"
definition = "cmake/ARMv8MML_DP.cmake"

[arch.ARMv8MML_DSP_DP]
cpu = "ARMV8MML"
definition = "cmake/ARMv8MML_DSP_DP.cmake"

[arch.ARMv81MML_DSP_DP_MVE_FP]
cpu = "ARMV81MML"
definition = "cmake/ARMv81MML_DSP_DP_MVE_FP.cmake"

[arch.ARMCA5]
cpu = "Cortex-A5"
definition = "cmake/ARMCA5.cmake"

[arch.ARMCA7]
cpu = "Cortex-A7"
definition = "cmake/ARMCA7.cmake"

[arch.ARMCA9]
cpu = "Cortex-A9"
definition = "cmake/ARMCA9.cmake"

