#!/bin/bash

xpl_path=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

cd ${xpl_path}/..

set -e

if [ ! -d cmsis ]
then
	cmsis_url="https://github.com/ARM-software/CMSIS_5/archive/5.7.0.tar.gz"
	curl -L $cmsis_url --progress-bar -o cmsis-5.7.0.tar.gz
	
	tar -xvf cmsis-5.7.0.tar.gz
	mv CMSIS_5-5.7.0 cmsis
	rm cmsis-5.7.0.tar.gz

	python3 -m venv env
	source env/bin/activate
	pip install lxml tomlkit
	
	# create arch configurations
	python pkg/pdsc-tools.py cmsis/ARM.CMSIS.pdsc
	rm -rf env
fi

if [ ! -d src/rtt ]
then
	segger_rtt=SEGGER_RTT_V688.tgz
	if [ ! -f $segger_rtt ]
	then
		echo "$segger_rtt not present, get it from jlink tgz and copy it in $(pwd)"
		exit 1
	fi

	mkdir -p src/rtt
	tar -xvf $segger_rtt
	mv SEGGER_RTT_V688/RTT/* src/rtt/
	rm -rf SEGGER_RTT_V688
fi
