#!/bin/bash

xpl_path=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

cd ${xpl_path}/..

set -e

if [ ! -d cmsis ]
then
	cmsis_url="https://github.com/ARM-software/CMSIS_5/archive/5.7.0.tar.gz"
	curl -L $cmsis_url --progress-bar -o cmsis-5.7.0.tar.gz
	
	tar -xvf cmsis-5.7.0.tar.gz
	mv CMSIS_5-5.7.0 cmsis
	rm cmsis-5.7.0.tar.gz
fi

python3 -m venv env
source env/bin/activate
pip install lxml tomlkit

# create arch configurations
python pkg/pdsc-tools.py cmsis/ARM.CMSIS.pdsc
rm -rf env
